[project]
name = "binance-datatool"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "aiohttp>=3.12.9",
    "colorama>=0.4.6",
    "polars>=1.30.0",
    "python-dateutil>=2.9.0.post0",
    "tqdm>=4.67.1",
    "typer>=0.16.0",
    "xmltodict>=0.14.2",
]
