# BHDS Coin-Margined Futures Holo K-line Resample Task
# Resample 1m holo klines to higher time frames

# Trade type - "spot", "futures/um", or "futures/cm"
trade_type: "futures/cm"

# Symbol selection - use either symbols list OR symbol_filter, not both
# If symbols is not null, symbol_filter is ignored
symbols: null

# Symbol filtering options - used only when symbols list is empty
symbol_filter:
  contract_type: "PERPETUAL" # Contract type: PERPETUAL or DELIVERY

# Target interval to resample to
resample_interval: "1h"
  
# Base offset for generating multiple offset files
# If null or "0m", only generate single file with 0m offset
# Otherwise, generate multiple offset files using resample_offsets method
base_offset: null

# BHDS home directory - main data storage directory
# If not set, uses environment variable BHDS_HOME, defaults to ~/crypto_data/bhds
# Input data from bhds_home/holo_1m_klines, output data to bhds_home/resampled_klines
bhds_home: null