# BHDS USDⓈ-Margined Futures Holo K-line Resample Task
# Resample 1m holo klines to higher time frames

# Trade type - "spot", "futures/um", or "futures/cm"
trade_type: "futures/um"

# Symbol selection - use either symbols list OR symbol_filter, not both
# If symbols is not null, symbol_filter is ignored
symbols: null

# Symbol filtering options - used only when symbols list is empty
symbol_filter:
  quote: "USDT" # USDT quote asset
  stable_pairs: false # Exclude stable pairs (e.g., USDC/USDT trading pairs)
  contract_type: "PERPETUAL" # Contract type: PERPETUAL or DELIVERY

# Target interval to resample to
resample_interval: "1h"
  
# Base offset for generating multiple offset files
# Only used when generate_offsets is true
base_offset: "5m"

# Data directories
# Use ~/crypto_data as $CRYPTO_BASE_DIR if not set

# Source directory for 1m holo kline parquet files
# Use $CRYPTO_BASE_DIR/binance_data/holo_1m_klines/ if not set
input_dir: null

# Output directory for resampled kline parquet files
# Use $CRYPTO_BASE_DIR/binance_data/resampled_klines/ if not set
output_dir: null
