# BHDS Coin-Margined Futures Funding Rate Download Task

# Data type, Options: "klines", "fundingRate", "metrics", "aggTrades", "liquidationSnapshot"
data_type: "fundingRate"

# Trade type, Options: "spot", "futures/um", "futures/cm"
trade_type: "futures/cm"

# Binance packaging frequency, Options: "daily", "monthly"
data_freq: "monthly"

# Symbol filtering
symbol_filter:
  contract_type: "PERPETUAL" # Contract type: PERPETUAL or DELIVERY

# Data configuration, local directory for downloads
# Use $CRYPTO_BASE_DIR/binance_data/aws_data/ if not set
# Use ~/crypto_data as $CRYPTO_BASE_DIR if not set
data_dir: null

# HTTP proxy, uses environment HTTP_PROXY if not set
http_proxy: null

# Checksum verification configuration
checksum_verification:
  delete_mismatch: true # Delete files on checksum mismatch
