# BHDS swap(USDT perpetuals) K-line Download Task

# Data type, Options: "klines", "fundingRate", "metrics", "aggTrades", "liquidationSnapshot"
data_type: "klines"

# Trade type, Options: "spot", "futures/um", "futures/cm"
trade_type: "futures/cm"

# AwsClient configuration
aws_client:
  # Binance packaging frequency, Options: "daily", "monthly"
  data_freq: "daily"

  # Binance supported Kline intervals, Options: "1m", "1h", "4h", "1d", etc.
  time_interval: "1m"

# Symbol filtering
symbol_filter:
  contract_type: "PERPETUAL" # Exclude leverage token pairs

# Data configuration, local directory for downloads
# Use $CRYPTO_BASE_DIR/binance_data/aws_data/ if not set
# Use ~/crypto_data as $CRYPTO_BASE_DIR if not set
data_dir: null

# HTTP proxy, uses environment HTTP_PROXY if not set
http_proxy: null

# Verification configuration
verification:
  delete_mismatch: true # Delete files on checksum mismatch
