# BHDS USDⓈ-Margined Futures aggTrades Download Task

# Data type, Options: "klines", "fundingRate", "metrics", "aggTrades", "liquidationSnapshot"
data_type: "aggTrades"

# Trade type, Options: "spot", "futures/um", "futures/cm"
trade_type: "futures/um"

# AwsClient configuration
aws_client:
  # Binance packaging frequency, Options: "daily", "monthly"
  data_freq: "daily"

# User-specified symbols
symbols: ["AUSDT"]

# Data configuration, local directory for downloads
# Use $CRYPTO_BASE_DIR/binance_data/aws_data/ if not set
# Use ~/crypto_data as $CRYPTO_BASE_DIR if not set
data_dir: null

# HTTP proxy, uses environment HTTP_PROXY if not set
http_proxy: null

# Verification configuration
verification:
  delete_mismatch: true # Delete files on checksum mismatch
