# BHDS USDⓈ-Margined Futures Funding Rate Download Task

# Data type, Options: "klines", "fundingRate", "metrics", "aggTrades", "liquidationSnapshot"
data_type: "fundingRate"

# Trade type, Options: "spot", "futures/um", "futures/cm"
trade_type: "futures/um"

# Binance packaging frequency, Options: "daily", "monthly"
data_freq: "monthly"

# Symbol filtering
symbol_filter:
  quote: "USDT" # USDT quote asset
  stable_pairs: false # Exclude stable pairs (e.g., USDC/USDT trading pairs)
  contract_type: "PERPETUAL" # Contract type: PERPETUAL or DELIVERY

# BHDS home directory for data storage
# If not set, uses environment variable BHDS_HOME, defaults to ~/crypto_data/bhds
# AWS data will be downloaded to bhds_home/aws_data
bhds_home: null

# HTTP proxy, uses environment HTTP_PROXY if not set
http_proxy: null

# Checksum verification configuration
checksum_verification:
  delete_mismatch: true # Delete files on checksum mismatch
