# BHDS Coin-Margined Futures K-line Parsing Task - Convert AWS data to Parquet and optionally complete with API

# Data type - must be "klines" for candlestick data
data_type: "klines"

# Trade type - "spot", "futures/um", or "futures/cm"
trade_type: "futures/cm"

# AWS data frequency - "daily" or "monthly"
data_freq: "daily"

# Kline interval - required for klines data type
# Supported intervals: "1m", "5m", "1h", "1d"
time_interval: "1m"

# Symbol selection - use either symbols list OR symbol_filter, not both
# If symbols is not null, symbol_filter is ignored
symbols: null

# Symbol filtering options - used only when symbols list is empty
symbol_filter:
  contract_type: "PERPETUAL" # Contract type: PERPETUAL or DELIVERY

# Enable API completion for missing data, only supported for daily frequency
enable_completion: true

# BHDS home directory for data storage
# If not set, uses environment variable BHDS_HOME, defaults to ~/crypto_data/bhds
# Reads raw data from bhds_home/aws_data as input, outputs to bhds_home/parsed_data
bhds_home: null

# Force re-processing of existing parquet files
force_update: false

# HTTP proxy, uses environment HTTP_PROXY if not set
http_proxy: null
