# BHDS USDⓈ-Margined Futures Funding Rate Parsing Task - Convert AWS data to Parquet and optionally complete with API

# Data type - must be "fundingRate" for funding rate data
data_type: "fundingRate"

# Trade type - "futures/um" or "futures/cm" for USDⓈ or Coin margined futures
trade_type: "futures/um"

# AWS data frequency - funding rates only support monthly
# Note: API completion is supported for monthly frequency
data_freq: "monthly"

# Symbol selection - use either symbols list OR symbol_filter, not both
# If symbols is non-empty, symbol_filter is ignored
symbols: null

# Symbol filtering options - used only when symbols list is empty
symbol_filter:
  quote: "USDT" # USDT quote asset
  stable_pairs: false # Exclude stable pairs (e.g., USDC/USDT trading pairs)

# Enable API completion for missing data
enable_completion: true

# BHDS home directory for data storage
# If not set, uses environment variable BHDS_HOME, defaults to ~/crypto_data/bhds
# Reads raw data from bhds_home/aws_data as input, outputs to bhds_home/parsed_data
bhds_home: null

# Force re-processing of existing parquet files
force_update: false

# HTTP proxy, uses environment HTTP_PROXY if not set
http_proxy: null
