# Parse AWS kline data to parquet and optionally complete with API

# Data type - must be "klines" for candlestick data
data_type: "klines"

# Trade type - "spot", "futures/um", or "futures/cm"
trade_type: "futures/um"

# AWS data frequency - "daily" or "monthly"
data_freq: "daily"

# Kline interval - required for klines data type
time_interval: "1m"

# Symbol selection - use either symbols list OR symbol_filter, not both
# If symbols is not null, symbol_filter is ignored
symbols: null

# Symbol filtering options - used only when symbols list is empty
symbol_filter:
  quote: "USDT" # USDT quote asset
  stable_pairs: false # Exclude stable coin pairs
  contract_type: "PERPETUAL"

# Enable API completion for missing data, only supported for daily frequency
enable_completion: true

# Data directories
# Use ~/crypto_data as $CRYPTO_BASE_DIR if not set

# Source directory for AWS downloaded files
# Use $CRYPTO_BASE_DIR/binance_data/aws_data/ if not set
aws_data_dir: null

# Output directory for parsed parquet files
# Use $CRYPTO_BASE_DIR/binance_data/parsed_data/ if not set
output_dir: null

# Force re-processing of existing parquet files
force_update: false

# HTTP proxy, uses environment HTTP_PROXY if not set
http_proxy: null
