# BHDS Spot 1m Holo K-line Synthesis Task
# Generate holographic 1-minute klines with VWAP

# Trade type - "spot", "futures/um", or "futures/cm"
trade_type: "spot"

# Symbol selection - use either symbols list OR symbol_filter, not both
# If symbols is not null, symbol_filter is ignored
symbols: null

# Symbol filtering options - used only when symbols list is empty
symbol_filter:
  quote: "USDT" # USDT quote asset
  stable_pairs: false # Exclude stable pairs (e.g., USDC/USDT trading pairs)
  leverage_tokens: false # Exclude leverage tokens (tokens with UP/DOWN/BULL/BEAR in name)

# Holo kline features
features:
  include_vwap: true # Include Volume Weighted Average Price

# Gap detection parameters
gap_detection:
  min_days: 1 # Minimum gap duration in days
  min_price_change: 0.1 # Minimum price change threshold (10%)

# BHDS home directory - main data storage directory
# If not set, uses environment variable BHDS_HOME, defaults to ~/crypto_data/bhds
# Input data from bhds_home/parsed_data, output data to bhds_home/holo_1m_klines
bhds_home: null
